### ISSUE TITLE
Basic schema text documentation

### ISSUE THREAD

**Issue by estiens** [psychonautwiki/bifrost#1]
Hi there,

I'm developing a harm reduction chatbot that is going to rely on pulling information from the psychnonaut wiki API. It would be super helpful to have a text document that lists the entire schema that could be returned -- something like

```
insufflated_afterglow_time_units, string, example value: 'minutes'
insufflated_comeup_time_units, string, example_value: 'minutes'
insufflated_dose_units, string, example_value: 'mg'
insufflated_heavy_dose, integer, example_value: 10
 ```

etc etc etc 

Also, an endpoint that could return all substances that one can currently get information about.

Let me know if there's any way I could help with this, thanks!

**Comment by KenanSulayman** [comment]
You can find more information regarding the schema here: https://github.com/psychonautwiki/bifrost/blob/master/server/graph/schema/rootQuery.js#L7-L196.

**Comment by estiens** [comment]
Great, thanks!

**Comment by KenanSulayman** [comment]
Swagger won't happen. GraphQL is _not_ a REST-API. Please try to get used to the GraphQL schemata provided as documentation in the API UI or - as previously mentioned - to the schema itself: https://github.com/psychonautwiki/bifrost/blob/master/server/graph/schema/rootQuery.js#L57-L223.
