### ISSUE TITLE
Some substances are returning an object instead of float for SubstanceRoaDose.treshold

### ISSUE THREAD

**Issue by dlbnco** [psychonautwiki/bifrost#15]
According to the schema, some properties in `SubstanceRoaDose` should be a float, but some substances are returning an object. I saw this happening with: 
- Prochlorperazine
- Cannabis

This results in GraphQLError like the following:

```json
{
  "errors": [
    {
      "locations": [
        {
          "column": 193,
          "line": 1
        }
      ],
      "message": "Float cannot represent non numeric value: { max: 2.5, min: 2 }",
      "path": [
        "substances",
        0,
        "roas",
        0,
        "dose",
        "threshold"
      ]
    }
  ]
}
```

**Comment by 19h** [comment]
Sorry, I never closed this issue but I resolved it shortly after you opening it. I also fixed an identical issue on https://psychonautwiki.org/wiki/Psilocybin_mushrooms.
