### ISSUE TITLE
Substance class strings have trailing hash character

### ISSUE THREAD

**Issue by wjlafrance** [psychonautwiki/bifrost#17]
This can be replicated with this query, encoded and linked [here](https://api.psychonautwiki.org/?query=%7B%0A%09%09substances%28query%3A%20"LSD"%29%20%7B%0A%09%09%09class%20%7B%0A%09%09%09%09chemical%0A%09%09%09%09psychoactive%0A%09%09%09%7D%0A%09%09%7D%0A%09%7D):

    {
      substances(query: "LSD") {
        class {
          chemical
          psychoactive
        }
      }
    }

The API currently responds:

    {"data":{"substances":[{"class":{"chemical":["Lysergamide#"],"psychoactive":["Psychedelics#"]}}]}}

The trailing `#` character is unexpected. This has been noticed in DoseBot for a few months now, and I believe it's a regression, but I'm not sure when it started happening.

**Comment by 19h** [comment]
It definitely started when I upgraded the semantics platform. I'll fix it.

**Comment by wjlafrance** [comment]
@19h thanks for the patch! It's confirmed fixed on my end.

**Comment by dlbnco** [comment]
I think it was fixed but just partially. It still showing up in some classes

```graphql
{
  substances(query: "Mirtazapine") {
    class {
      chemical
      psychoactive
    }
  }
}
```
```json
{
  "data": {
    "substances": [
      {
        "class": {
          "chemical": [
            "Piperazinoazepine"
          ],
          "psychoactive": [
            "Antidepressant#,Sedative#,Psychedelics"
          ]
        }
      }
    ]
  }
}
```

**Comment by 19h** [comment]
It also not supposed to deliver the classes as a single string..

**Comment by 19h** [comment]
I’m currently traveling in the arctic cycle and have limited access to computer infrastructure. I will fix this issue when I’m back. Thanks for reporting the issue!

**Comment by 19h** [comment]
Issue should be resolved.
