### ISSUE TITLE
Most forms of administration are missing dose units

### ISSUE THREAD

**Issue by estiens** [psychonautwiki/bifrost#2]
For most substances it seems as only the oral form of administration contains dose units, the other forms of administration contain the numeric data on dose thresholds, but not the units.

For example:
https://psychonautwiki.org/w/api.php?action=browsebysubject&subject=meth

**Comment by KenanSulayman** [comment]
Sorry for the delay, several technical issues in the underlying platform needed to be addressed before further changes to the API became viable.

This will be addressed by #3, allowing you to access all available data in an array-structure.

Wether this will help you still needs to be worked-out, so please let me know if this satisfies your request.

**Comment by estiens** [comment]
I am now using dosage information from Psychonaut Wiki for the Caterpillar Bot for substances where it is available. I ran a quick report to see which ones had dosing numbers, but no dosing units. Hopefully this helps.

Missing Insufflation Dose Units: 2ce, mpa, noopept, methamphetamine, theacrine, pentedrone
Missing Oral Dose Units: ibogaine, alcohol, noopept, 3-ho-pce, cannabis, 3-ho-pcp
Missing IV Dose Units: methamphetamine, heroin
Missing Smoked Dose Units: 5f-akb48, methaqualone, 5-meo-dalt

**Comment by ClarityPSY** [comment]
Hi estiens, thank you for pointing this out. I am working on adding the dose unit markup for these substances now. Cheers.

**Comment by KenanSulayman** [comment]
test

**Comment by ClarityPSY** [comment]
Hi estiens, thank you for pointing this out. I am working on adding the dose unit markup for these substances now. Cheers.

EDIT: They should all be fixed. The only exception is ibogaine, in which the doses are given in terms of mg/kg, so I just omitted dose units for it to save on confusion for our API users.

Let me know if I missed anything. Thanks.
