### ISSUE TITLE
Unable to query API for 2C-B effects

### ISSUE THREAD

**Issue by predme** [psychonautwiki/bifrost#24]
I haven't been able to get the effects data for 2C-B using the API.

Example:

```
{
    substances(query: "2cb") {
    		name
    
        # subjective effects
        effects {
            name url
        }
   }
}
```

Returns this:
```
{
  "data": {
    "substances": [
      {
        "effects": [],
        "name": "2C-B"
      }
    ]
  }
}
```

It's able to query 2C-B itself but the effects are missing despite the wiki page containing them.

**Comment by 19h** [comment]
Thanks for reporting. I'll look into it.

**Comment by 19h** [comment]
We determined that parts of our semantic metadata infrastructure are currently having an outage. This is hopefully resolved soon. I will keep this thread updated.

**Comment by 19h** [comment]
Effects should be restored.
