### ISSUE TITLE
API is returning 502 response suddenly. Unable to fetch any substance information.

### ISSUE THREAD

**Issue by uddipan978** [psychonautwiki/bifrost#36]
Please fix this issue ASAP. I've used your API in my mobile app and website. Now your API is down and for that my app and website is also unable to fetch any substance related information. This is very important for me.
![Screenshot from 2021-03-06 14-21-52](https://user-images.githubusercontent.com/65089098/110201262-2963f200-7e88-11eb-90aa-92749d71d9e3.png)

**Comment by 19h** [comment]
Should be fixed? I'll close this issue.
