### ISSUE TITLE
Remove the "Language changed from English" popup

### ISSUE THREAD

**Issue by davidhedlund** [psychonautwiki/bifrost#5]
I get this message popup very often when I visit PW (logged in or not):

> "Language changed from English"

Can you please make remove it?

My language is set to British (it was default).

**Comment by KenanSulayman** [comment]
This is not related to the Bifrost API. Please create an issue in JIRA / PSY.

**Comment by davidhedlund** [comment]
@KenanSulayman Did I file it in the right place this time?: https://psychonaut.atlassian.net/browse/PSY-68
