### ISSUE TITLE
Legacy API deprecation, sunset period and retirement

### ISSUE THREAD

**Issue by KenanSulayman** [psychonautwiki/bifrost#7]
Dear developers,

**we have deprecated our legacy MediaWiki API and are sunsetting it until its retirement on April 19th, 2018**. Bifrost will herewith be promoted to be the default and only PsychonautWiki API.

## Motivation

The legacy API has regularly been used as a way of attacking the PsychonautWiki, or to scrape the wiki in ways that violate our guidelines. Even though we love all developers, protecting the sanctity of the availability of the PsychonautWiki for all users is our utmost priority.

The Bifrost API infrastructure has been engineered with efficiency in mind. Every single component has been fine-tuned to cope with high traffic scenarios -- from Redis to the in-memory LRU cache to the Varnish caching proxy between Bifrost and PW itself. It's by design scalable.

Bifrost entered sunrise almost a year ago and we urged any developer to communicate needs in that period. There are open issues, but they are not trivial to implement with the legacy MediaWiki API as well.

## Potential issues

If you have previously used our legacy MediaWiki API to programmatically query effects et al. from the PsychonautWiki, you will need to migrate to the GraphQL API as provided by Bifrost. Please note that the legacy MediaWIKI API has never been supported by us.

## Roadmap

- **April 5th, 2018**: Sunsetting of legacy MediaWiki API
- **April 19th, 2018**: Retirement of legacy MediaWiki API

Please inform us of potential issues with your client code affected by the removal of our legacy API. **If you require support migrating to Bifrost or require features to be implemented, you can contact me via E-Mail at [kenan@psychonaut.wiki](mailto:kenan@psychonaut.wiki) or [via Telegram](https://t.me/kenansulayman).**

**Comment by estiens** [comment]
Is there an overview of the API - methods, parameters, authorization, etc? I'll likely need to make use of it for the Caterpillar bot. (I only hit the API once every week or so, but I use it to update any substances that have been updated)

**Comment by estiens** [comment]
I would still like a Swagger (or similar) document to make sure I am using the API correctly and getting all information from it. If there's interest, I could see about putting one together

**Comment by KenanSulayman** [comment]
@estiens Can you elaborate on how a swagger documentation would provide information beyond the _Documentation Explorer_ as provided by [GraphiQL](https://api.psychonautwiki.org/)?

**Comment by mikepsinn** [comment]
@KenanSulayman Thanks for all your great work!  

Is https://api.psychonautwiki.org/ still the correct link?  It won't load for me.

**Comment by KenanSulayman** [comment]
@mikepsinn You’re welcome!

There was a downtime of 450 seconds at 02:03 ZULU while the server was performing at automated system upgrade (specifically an upgrade to CoreOS 1745).

Service should have recovered. Please let me know if you’re still seeing issues.
