### ISSUE TITLE
 links are not loading on tor

### ISSUE THREAD

**Issue by Viviviolets** [psychonautwiki/bifrost#9]
I dont know if the links provided are working but I was hopping to check them out. I listed the ones that I am having issues loading using on Tor. Maybe the site is down?

https://vvedndyt433kopnhv6vejxnut54y5752vpxshjaqmj7ftwiu6quiv2ad.onion/wiki/Main_Page

https://psychonaut3z5aoz.onion/wiki/Main_Page

**Comment by KenanSulayman** [comment]
Thanks for your report.

The backend systems in question seem normative, but I replicated the issue and will replaced the responsible servers. Once the hidden services are accepted into the network consensus they will be back, which might take a few hours. I will monitor their recovery.

**Comment by KenanSulayman** [comment]
Thanks for your report.

The backend systems in question seem normative, but I replicated the issue and will replace the responsible servers. Once the hidden services are accepted into the network consensus they will be back, which might take a few hours. I will monitor their recovery.

**Comment by KenanSulayman** [comment]
After further consideration I concluded this issue is invalid. You are trying to load the hidden services via TLS, which does not work.

Disable HTTPS Anywhere, if needed.

Working URLs:

http://vvedndyt433kopnhv6vejxnut54y5752vpxshjaqmj7ftwiu6quiv2ad.onion/wiki/Main_Page
http://psychonaut3z5aoz.onion/wiki/Main_Page

**Comment by KenanSulayman** [comment]
Sorry, it was my fault. Our https forwarded wasn't aware of hidden services and redirected requests to them to their https version, which is wrong. I fixed it. Thanks again.
